NEP = {
'A' : {
        'NEP' : 2021,
        'hh' : 1,
        'pv' : .09,
        'hp' : .02,
        'heat' : 1,
        'ev_rsu' : .02,
        'ev_urb' : .01,
        'bss' : .04,
      },
'B' : {
        'NEP' : 2037,
        'hh' : .9,
        'pv' : .34,
        'hp' : .62,
        'heat' : 2,
        'ev_rsu' : .87,
        'ev_urb' : .6,
        'bss' : .52,
      },
'C' : {
        'NEP' : 2045,
        'hh' : .9,
        'pv' : .44,
        'hp' : .7,
        'heat' : 3,
        'ev_rsu' : 1.19,
        'ev_urb' : .83,
        'bss' : .68,
      },
'X' : {
        'NEP' : 9999,
        'hh' : 1,
        'pv' : 1,
        'hp' : 1,
        'heat' : 1,
        'ev_rsu' : 1,
        'ev_urb' : 1,
        'bss' : 1,
      },
}
